# FinancialMk has no business model — it's MIT-licensed and self-hostable.
# If it saves you a Bloomberg/Morningstar/SimplyWallSt subscription and you
# can afford it, sponsoring keeps the lights on.

github: AlejandroPerezPaniagua0
